import Head from "next/head";

const Title = () => {
    return ( 
        <Head>
        <title>TrackFit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icone.ico" />
      </Head>
     );
}
 
export default Title;